import {
  el,
  onReset,
  showOverlay,
  hideOverlay,
  sound,
  getCellSize,
  getGameArea,
  getHighScore,
  setHighScore,
} from "../../../shared/utils";

// Number Slide — the classic 15-puzzle. Boards are generated by performing
// random legal slides from the solved state, which guarantees solvability.

const SIZE = 4;

let board: number[][];
let emptyPos: { r: number; c: number };
let moves = 0;
let best = 0;
let over = false;

function getCellSizeLocal() {
  const area = getGameArea();
  const size = Math.min(area.w, area.h) / SIZE;
  return Math.max(35, Math.min(size, 70));
}

function draw() {
  const gameEl = el("number-slide");
  if (!gameEl) return;
  gameEl.innerHTML = "";
  const CELL = getCellSizeLocal();
  const total = SIZE * CELL;
  gameEl.style.width = total + "px";
  gameEl.style.height = total + "px";
  gameEl.style.position = "relative";
  gameEl.style.left = "50%";
  gameEl.style.top = "50%";
  gameEl.style.transform = "translate(-50%, -50%)";

  for (let r = 0; r < SIZE; r++) {
    for (let c = 0; c < SIZE; c++) {
      const val = board[r][c];
      if (val === 0) continue;
      const tile = document.createElement("button");
      tile.className =
        "absolute flex items-center justify-center rounded-lg bg-white/10 border-2 border-white/20 text-xl sm:text-2xl font-bold text-white hover:bg-white/20 transition-colors";
      tile.style.left = c * CELL + "px";
      tile.style.top = r * CELL + "px";
      tile.style.width = CELL - 2 + "px";
      tile.style.height = CELL - 2 + "px";
      tile.textContent = String(val);
      tile.dataset.r = String(r);
      tile.dataset.c = String(c);
      tile.setAttribute("aria-label", `Tile ${val}`);
      tile.addEventListener("click", () => tryMove(r, c));
      gameEl.appendChild(tile);
    }
  }
}

function createBoard() {
  board = [];
  let n = 1;
  for (let r = 0; r < SIZE; r++) {
    board[r] = [];
    for (let c = 0; c < SIZE; c++) {
      board[r][c] = n <= SIZE * SIZE - 1 ? n : 0;
      n++;
    }
  }
  emptyPos = { r: SIZE - 1, c: SIZE - 1 };

  // Shuffle with random legal slides (blank swaps with a random neighbour).
  const steps = 200;
  for (let i = 0; i < steps; i++) {
    const neighbors: [number, number][] = [];
    const { r, c } = emptyPos;
    if (r > 0) neighbors.push([r - 1, c]);
    if (r < SIZE - 1) neighbors.push([r + 1, c]);
    if (c > 0) neighbors.push([r, c - 1]);
    if (c < SIZE - 1) neighbors.push([r, c + 1]);
    const [nr, nc] = neighbors[Math.floor(Math.random() * neighbors.length)];
    board[emptyPos.r][emptyPos.c] = board[nr][nc];
    board[nr][nc] = 0;
    emptyPos = { r: nr, c: nc };
  }
  // Avoid starting already solved.
  if (checkWin()) return createBoard();
}

function canMove(r: number, c: number): boolean {
  const er = emptyPos.r;
  const ec = emptyPos.c;
  return (
    (Math.abs(r - er) === 1 && c === ec) ||
    (Math.abs(c - ec) === 1 && r === er)
  );
}

function tryMove(r: number, c: number) {
  sound.click();
  if (over || !canMove(r, c)) return;
  board[emptyPos.r][emptyPos.c] = board[r][c];
  board[r][c] = 0;
  emptyPos = { r, c };
  moves++;
  sound.click();
  if (checkWin()) {
    over = true;
    best = setHighScore("number-slide", moves, true);
    const status = el("status");
    if (status) status.textContent = `Solved in ${moves} moves · Best: ${best}`;
    sound.win();
    showOverlay("Solved!", `You finished in ${moves} move${moves === 1 ? "" : "s"}. Best: ${best}.`);
  } else {
    const status = el("status");
    if (status) status.textContent = `Moves: ${moves}`;
    draw();
  }
}

function checkWin(): boolean {
  let expected = 1;
  for (let r = 0; r < SIZE; r++) {
    for (let c = 0; c < SIZE; c++) {
      if (r === SIZE - 1 && c === SIZE - 1) return board[r][c] === 0;
      if (board[r][c] !== expected) return false;
      expected++;
    }
  }
  return true;
}

function reset() {
  moves = 0;
  over = false;
  best = getHighScore("number-slide");
  createBoard();
  draw();
  const status = el("status");
  if (status) status.textContent = `Moves: 0 · Best: ${best}`;
  hideOverlay();
}

export function initGame() {
  onReset(reset);
  reset();
}
